### PR TITLE
404, translations and optional multilang

### PR DESCRIPTION
**Pull request by spech66**
Hello. this PR includes the following:
- Themed 404 page
- Translation of basic strings (read more, ...) according to the languageName setting
- Optional multilang support. Remove comment from example page settings allows the page to work in multiple languages. (German example included).

Best regards
Sebastian

### CODE REVIEW

**Comment by somratpro** [comment]
Hello @spech66 

Thanks for your activity, we really appreciate that. but we use [translation by content directory](https://gohugo.io/content-management/multilingual/#translation-by-content-directory) for multilingual, this really helps when the user chooses to use forestry.

**Comment by spech66** [comment]
Hi @somratpro thank you for the feedback. I will have a look in this. Does this work with the data and i18n files as well?

**Comment by somratpro** [comment]
Yes, of course

**Comment by spech66** [comment]
I migrated the content folder and tried to get the other approach running as well. However according to the docs and [bep](https://discourse.gohugo.io/t/multilingual-data-files/4684) the PR would still be required to get data and i18n working or am I missing something? :-)

**Pull request merged**
